[package]
name = "day_three_1"
version = "0.1.0"
authors = ["Andre Zanellato <andre.zanellato@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.4"
geo-types = "0.4.3"
